databases:
  - name: core
    type: mongo
    host: 127.0.0.1
    port: 27017
    database: nutrix
    username: ""
    password: ""
    tables: # this is to allow changing the following specific table names
      sales: sales

uploads_path: "./mnt/public"
  
zitadel:
  domain: "zitadel"
  port: 8080
  key_path: "./mnt/zitadel-key.json" # this is the path to your zitadel key related to your root directory of backend
  enabled: true

serve_frontend: false
  
timezone: Africa/Cairo
env: dev