name: CD
run-name: Packaging a new nutrixpos version 🚀
on:
  push:
    tags:
      - "v*.*.*"

# required to create releases
permissions:
  contents: write

env:
  HUSKY: "0"

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  package-windows:
    runs-on: windows-latest
    needs: ci
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: create nsis-runtime directory
        run: |
            # Create directory if it doesn't exist
            if (!(Test-Path -Path "./nsis-runtime")) {
              New-Item -ItemType Directory -Path "./nsis-runtime" -Force
            }

      - name: Download earlier artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./nsis-runtime/frontend

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-windows64
          path: ./nsis-runtime

      - name: Install NSIS using Chocolatey
        run: choco install nsis -y

      - name: Download required files to nsis-runtime
        run: |

          dir
          cd .\nsis-runtime
          dir
          cd ..\
          tree /f assets

          # Download files using PowerShell
          Invoke-WebRequest -Uri "https://elmawardy.sirv.com/nutrix-icon-0.ico" -OutFile "./nsis-runtime/icon.ico"
          Invoke-WebRequest -Uri "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-8.2.1-signed.msi" -OutFile "./nsis-runtime/mongodb-windows-x86_64-8.2.1-signed.msi"

          Copy-Item -Path "./package.nsi" -Destination "./nsis-runtime/package.nsi" -Force
          Copy-Item -Path "./LICENSE" -Destination "./nsis-runtime/license.txt" -Force
          (Get-Content ./config.example.yaml) -replace 'host: 127.0.0.1', 'host: ""' | Set-Content ./config.example.yaml
          Copy-Item -Path "./config.example.yaml" -Destination "./nsis-runtime/config.yaml" -Force
          Copy-Item -Path "./assets/" -Destination "./nsis-runtime/assets" -Force -Recurse
          (Get-Content ./nsis-runtime/package.nsi) -replace 'nutrixpos-installer\.exe', "nutrixpos-${{github.ref_name}}-windows64.exe" | Set-Content ./nsis-runtime/package.nsi

          cd .\nsis-runtime
          tree /f

          & "C:\Program Files (x86)\NSIS\makensis.exe" ./package.nsi

      - name: Create Release and Upload windows64 package.
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./nsis-runtime/nutrixpos-${{github.ref_name}}-windows64.exe
